# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: generation-tempalte Package

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18.16
          registry-url: https://registry.npmjs.org/
      - run: pnpm install
      - name: 'Git Configure'
        uses: dawidd6/action-git-user-config@v1.0.0
        with:
          token: ${{github.token}}
          username: ${{github.actor}}
      - run: pnpm build
      - name: 'Commit Build'
        uses: matheusalbino/git-commit@v1.0.1
        with: 
          github-token: ${{github.token}}
          message: 'ci(release): build dist'
      - run: pnpm release
      - name: 'Git Push'
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{github.token}}
          push-branch: master

  publish-npm:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: git pull
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
